"use server";

import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { parseDecimalToMinorUnits, assertSupportedCurrency } from "@/lib/money";
import { requirePermission } from "@/modules/organizations/current-organization";
import { runAction, type ActionState } from "@/server/actions/action-state";
import { getServices } from "@/server/container";

const schema = z.object({
  amount: z.string().trim().regex(/^\d{1,9}([.,]\d{1,2})?$/, "Valor inválido"),
  /** Generated by the client per dialog session so retries never duplicate a payout. */
  requestId: z.string().uuid().optional(),
});

export async function requestPayout(_prev: ActionState, formData: FormData): Promise<ActionState> {
  return runAction(async () => {
    const { organization, userId } = await requirePermission("payouts:request");
    const input = schema.parse({ amount: formData.get("amount"), requestId: formData.get("requestId") ?? undefined });
    const currency = assertSupportedCurrency(organization.defaultCurrency);

    await getServices().payouts.request({
      organizationId: organization.id,
      amount: parseDecimalToMinorUnits(input.amount, currency),
      currency,
      idempotencyKey: `payout:${organization.id}:${input.requestId ?? randomUUID()}`,
      userId,
    });

    revalidatePath("/payouts");
    revalidatePath("/finance");
    return { status: "success", message: "Saque solicitado. Você será notificado quando for pago." };
  });
}
